Added extra checks to pmmove and cleaned up update a bit.

diff --git a/pmmove b/pmmove
--- a/pmmove
+++ b/pmmove
@@ -1,9 +1,15 @@
 #!/bin/csh
 
-### Checks Portmaster log for moved ports and 
-### then changes their origin.
+### Checks Portmaster log for moved ports and changes
+### their origin either using portmaster or pkg.
 
 ## INIT section (don't change)
+
+if ! { fuser portmaster.log >& /dev/null } then
+	echo "Portmaster logfile currently in use, exiting!"	> /dev/stderr
+	echo "(did you run refresh recently?)"			> /dev/stderr
+	exit 1;
+endif
 
 if ("`grep moved portmaster.log`" == "") then
 	echo "No moved ports to process, exiting!"		> /dev/stderr
@@ -16,6 +22,10 @@ if ($1 == "pkg") then
 	set pkg=1
 else
 	set pkg=0
+	if ! { pkg info -e portmaster } then
+	   echo "ports-mgmt/portmaster not installed (required)" > /dev/stderr
+	   exit 1;
+	endif
 endif
 
 ## MAIN section
@@ -26,11 +36,20 @@ foreach a ("`grep moved portmaster.log`")
 	set new=`echo "$a" | cut -d ' ' -f7`;
 
 	if ($pkg == 1) then
-		pkg set -yo $old\:$new;
+		if { pkg set -yo $old\:$new; } then
+			echo "Changed origin: $old => $new";
+		else
+			echo "Something went wrong.."		> /dev/stderr
+			exit 1
+		endif
 	else
-		portmaster -o $new $old_pm
+		if { portmaster -o $new $old_pm } then
+			echo "Port moved: $old => $new";
+		else
+			echo "Something went wrong.."		> /dev/stderr
+			exit 1
+		endif
 	endif
-	echo "Changed: $old => $new";
 end
 
 echo "Finished changing port origin(s), now refreshing port updates."
