Added a check for Portmaster installation.
Signed-off-by: ShelLuser <ShelLuser@users.noreply.github.com>

diff --git a/refresh b/refresh
--- a/refresh
+++ b/refresh
@@ -6,6 +6,11 @@ WP=`dirname $0`
 ME=`basename $0`
 udate=`stat -f %Sa -t %Y%m%d $WP/$0.meta`
 
+if [ ! `pkg -e portmaster` ]; then
+	echo "ports-mgmt/portmaster not installed (required)"	> /dev/stderr
+	exit 1;
+fi
+
 if [ -n "$udate" ]; then
 	ucmd="-d $udate";
 fi;
